local_name: "github.com/Muxi-X/forum-be/microservice/gateway"  # 服务名称///
tracing:
  jager: "localhost:12345"  # Jaeger 跟踪服务的地址///

hashids:
  salt: "12345678"
  minlength: 5
  #`````````````````

runmode: debug               # 开发模式, debug, release, test 部署时环境变量覆盖
addr: :8080                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: 12345678
log:
  writers: file,stdout # 部署时输出到 stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7

db:  # DB 配置 部署时环境变量覆盖
  name: forum
  addr: 127.0.0.1:3306
  username: root
  password: 123456
redis:
  addr: 127.0.0.1:6379
  password: ""
blacklist:
  tidy_time: 24 # 自动清理过期数据的间隔时间(hour)
oss:
  access_key: 12345
  secret_key: 12345
  bucket_name: 12345
  domain_name: http://12345 # CDN 域名


etcd:
  addr: "127.0.0.1:2379"
  username: "root"
  password: "123456"
