// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.4
// source: user.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMessageRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreatePrivateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendId        uint32                 `protobuf:"varint,1,opt,name=send_id,json=sendId,proto3" json:"send_id,omitempty"`
	ReceiveId     uint32                 `protobuf:"varint,2,opt,name=receive_id,json=receiveId,proto3" json:"receive_id,omitempty"`
	PostId        uint32                 `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CommentId     uint32                 `protobuf:"varint,4,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrivateMessageRequest) Reset() {
	*x = CreatePrivateMessageRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrivateMessageRequest) ProtoMessage() {}

func (x *CreatePrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreatePrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePrivateMessageRequest) GetSendId() uint32 {
	if x != nil {
		return x.SendId
	}
	return 0
}

func (x *CreatePrivateMessageRequest) GetReceiveId() uint32 {
	if x != nil {
		return x.ReceiveId
	}
	return 0
}

func (x *CreatePrivateMessageRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CreatePrivateMessageRequest) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CreatePrivateMessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreatePrivateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeletePrivateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePrivateMessageRequest) Reset() {
	*x = DeletePrivateMessageRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePrivateMessageRequest) ProtoMessage() {}

func (x *DeletePrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*DeletePrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePrivateMessageRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeletePrivateMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageRequest) Reset() {
	*x = ListMessageRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageRequest) ProtoMessage() {}

func (x *ListMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageRequest.ProtoReflect.Descriptor instead.
func (*ListMessageRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListMessageRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageResponse) Reset() {
	*x = ListMessageResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageResponse) ProtoMessage() {}

func (x *ListMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageResponse.ProtoReflect.Descriptor instead.
func (*ListMessageResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *ListMessageResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type StudentLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentLoginRequest) Reset() {
	*x = StudentLoginRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentLoginRequest) ProtoMessage() {}

func (x *StudentLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentLoginRequest.ProtoReflect.Descriptor instead.
func (*StudentLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *StudentLoginRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Info          *UserInfo              `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInfoRequest) Reset() {
	*x = UpdateInfoRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfoRequest) ProtoMessage() {}

func (x *UpdateInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateInfoRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateInfoRequest) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint32               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetInfoRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TeamLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OauthCode     string                 `protobuf:"bytes,1,opt,name=oauth_code,json=oauthCode,proto3" json:"oauth_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamLoginRequest) Reset() {
	*x = TeamLoginRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamLoginRequest) ProtoMessage() {}

func (x *TeamLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamLoginRequest.ProtoReflect.Descriptor instead.
func (*TeamLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *TeamLoginRequest) GetOauthCode() string {
	if x != nil {
		return x.OauthCode
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type UserInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                     string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl                 string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Signature                 string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	IsPublicCollectionAndLike bool                   `protobuf:"varint,6,opt,name=is_public_collection_and_like,json=isPublicCollectionAndLike,proto3" json:"is_public_collection_and_like,omitempty"`
	IsPublicFeed              bool                   `protobuf:"varint,7,opt,name=is_public_feed,json=isPublicFeed,proto3" json:"is_public_feed,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *UserInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserInfo) GetIsPublicCollectionAndLike() bool {
	if x != nil {
		return x.IsPublicCollectionAndLike
	}
	return false
}

func (x *UserInfo) GetIsPublicFeed() bool {
	if x != nil {
		return x.IsPublicFeed
	}
	return false
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *UserInfoResponse) GetList() []*UserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type UserProfile struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role                      string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Avatar                    string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email                     string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Signature                 string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	IsPublicFeed              bool                   `protobuf:"varint,7,opt,name=is_public_feed,json=isPublicFeed,proto3" json:"is_public_feed,omitempty"`
	IsPublicCollectionAndLike bool                   `protobuf:"varint,8,opt,name=is_public_collection_and_like,json=isPublicCollectionAndLike,proto3" json:"is_public_collection_and_like,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserProfile) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfile) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserProfile) GetIsPublicFeed() bool {
	if x != nil {
		return x.IsPublicFeed
	}
	return false
}

func (x *UserProfile) GetIsPublicCollectionAndLike() bool {
	if x != nil {
		return x.IsPublicCollectionAndLike
	}
	return false
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        uint32                 `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *ListRequest) GetLastId() uint32 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	List          []*User                `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *ListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListResponse) GetList() []*User {
	if x != nil {
		return x.List
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"I\n" +
	"\x14CreateMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x01\n" +
	"\x1bCreatePrivateMessageRequest\x12\x17\n" +
	"\asend_id\x18\x01 \x01(\rR\x06sendId\x12\x1d\n" +
	"\n" +
	"receive_id\x18\x02 \x01(\rR\treceiveId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\rR\x06postId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x04 \x01(\rR\tcommentId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\"F\n" +
	"\x1bDeletePrivateMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"-\n" +
	"\x12ListMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"1\n" +
	"\x13ListMessageResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages\"P\n" +
	"\x13StudentLoginRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"G\n" +
	"\x11UpdateInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\"\n" +
	"\x04info\x18\x02 \x01(\v2\x0e.user.UserInfoR\x04info\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\"\n" +
	"\x0eGetInfoRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\rR\x03ids\"W\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"1\n" +
	"\x10TeamLoginRequest\x12\x1d\n" +
	"\n" +
	"oauth_code\x18\x01 \x01(\tR\toauthCode\"H\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fredirect_url\x18\x02 \x01(\tR\vredirectUrl\"\xe9\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12@\n" +
	"\x1dis_public_collection_and_like\x18\x06 \x01(\bR\x19isPublicCollectionAndLike\x12$\n" +
	"\x0eis_public_feed\x18\a \x01(\bR\fisPublicFeed\"6\n" +
	"\x10UserInfoResponse\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.user.UserInfoR\x04list\"\xf9\x01\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12$\n" +
	"\x0eis_public_feed\x18\a \x01(\bR\fisPublicFeed\x12@\n" +
	"\x1dis_public_collection_and_like\x18\b \x01(\bR\x19isPublicCollectionAndLike\"h\n" +
	"\vListRequest\x12\x17\n" +
	"\alast_id\x18\x01 \x01(\rR\x06lastId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"D\n" +
	"\fListResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12\x1e\n" +
	"\x04list\x18\x02 \x03(\v2\n" +
	".user.UserR\x04list\"\t\n" +
	"\aRequest\"\n" +
	"\n" +
	"\bResponse\"\x8b\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role2\xd1\x05\n" +
	"\vUserService\x12:\n" +
	"\tTeamLogin\x12\x16.user.TeamLoginRequest\x1a\x13.user.LoginResponse\"\x00\x12@\n" +
	"\fStudentLogin\x12\x19.user.StudentLoginRequest\x1a\x13.user.LoginResponse\"\x00\x129\n" +
	"\aGetInfo\x12\x14.user.GetInfoRequest\x1a\x16.user.UserInfoResponse\"\x00\x123\n" +
	"\n" +
	"GetProfile\x12\x10.user.GetRequest\x1a\x11.user.UserProfile\"\x00\x12/\n" +
	"\x04List\x12\x11.user.ListRequest\x1a\x12.user.ListResponse\"\x00\x12D\n" +
	"\vListMessage\x12\x18.user.ListMessageRequest\x1a\x19.user.ListMessageResponse\"\x00\x12K\n" +
	"\x12ListPrivateMessage\x12\x18.user.ListMessageRequest\x1a\x19.user.ListMessageResponse\"\x00\x12=\n" +
	"\rCreateMessage\x12\x1a.user.CreateMessageRequest\x1a\x0e.user.Response\"\x00\x12K\n" +
	"\x14CreatePrivateMessage\x12!.user.CreatePrivateMessageRequest\x1a\x0e.user.Response\"\x00\x12K\n" +
	"\x14DeletePrivateMessage\x12!.user.DeletePrivateMessageRequest\x1a\x0e.user.Response\"\x00\x127\n" +
	"\n" +
	"UpdateInfo\x12\x17.user.UpdateInfoRequest\x1a\x0e.user.Response\"\x00B\tZ\a./protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_proto_goTypes = []any{
	(*CreateMessageRequest)(nil),        // 0: user.CreateMessageRequest
	(*CreatePrivateMessageRequest)(nil), // 1: user.CreatePrivateMessageRequest
	(*DeletePrivateMessageRequest)(nil), // 2: user.DeletePrivateMessageRequest
	(*ListMessageRequest)(nil),          // 3: user.ListMessageRequest
	(*ListMessageResponse)(nil),         // 4: user.ListMessageResponse
	(*StudentLoginRequest)(nil),         // 5: user.StudentLoginRequest
	(*UpdateInfoRequest)(nil),           // 6: user.UpdateInfoRequest
	(*GetRequest)(nil),                  // 7: user.GetRequest
	(*GetInfoRequest)(nil),              // 8: user.GetInfoRequest
	(*RegisterRequest)(nil),             // 9: user.RegisterRequest
	(*TeamLoginRequest)(nil),            // 10: user.TeamLoginRequest
	(*LoginResponse)(nil),               // 11: user.LoginResponse
	(*UserInfo)(nil),                    // 12: user.UserInfo
	(*UserInfoResponse)(nil),            // 13: user.UserInfoResponse
	(*UserProfile)(nil),                 // 14: user.UserProfile
	(*ListRequest)(nil),                 // 15: user.ListRequest
	(*ListResponse)(nil),                // 16: user.ListResponse
	(*Request)(nil),                     // 17: user.Request
	(*Response)(nil),                    // 18: user.Response
	(*User)(nil),                        // 19: user.User
}
var file_user_proto_depIdxs = []int32{
	12, // 0: user.UpdateInfoRequest.info:type_name -> user.UserInfo
	12, // 1: user.UserInfoResponse.list:type_name -> user.UserInfo
	19, // 2: user.ListResponse.list:type_name -> user.User
	10, // 3: user.UserService.TeamLogin:input_type -> user.TeamLoginRequest
	5,  // 4: user.UserService.StudentLogin:input_type -> user.StudentLoginRequest
	8,  // 5: user.UserService.GetInfo:input_type -> user.GetInfoRequest
	7,  // 6: user.UserService.GetProfile:input_type -> user.GetRequest
	15, // 7: user.UserService.List:input_type -> user.ListRequest
	3,  // 8: user.UserService.ListMessage:input_type -> user.ListMessageRequest
	3,  // 9: user.UserService.ListPrivateMessage:input_type -> user.ListMessageRequest
	0,  // 10: user.UserService.CreateMessage:input_type -> user.CreateMessageRequest
	1,  // 11: user.UserService.CreatePrivateMessage:input_type -> user.CreatePrivateMessageRequest
	2,  // 12: user.UserService.DeletePrivateMessage:input_type -> user.DeletePrivateMessageRequest
	6,  // 13: user.UserService.UpdateInfo:input_type -> user.UpdateInfoRequest
	11, // 14: user.UserService.TeamLogin:output_type -> user.LoginResponse
	11, // 15: user.UserService.StudentLogin:output_type -> user.LoginResponse
	13, // 16: user.UserService.GetInfo:output_type -> user.UserInfoResponse
	14, // 17: user.UserService.GetProfile:output_type -> user.UserProfile
	16, // 18: user.UserService.List:output_type -> user.ListResponse
	4,  // 19: user.UserService.ListMessage:output_type -> user.ListMessageResponse
	4,  // 20: user.UserService.ListPrivateMessage:output_type -> user.ListMessageResponse
	18, // 21: user.UserService.CreateMessage:output_type -> user.Response
	18, // 22: user.UserService.CreatePrivateMessage:output_type -> user.Response
	18, // 23: user.UserService.DeletePrivateMessage:output_type -> user.Response
	18, // 24: user.UserService.UpdateInfo:output_type -> user.Response
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
